server:
 port: 7900
spring:
 jpa:
  generate-ddl: false
  show-sql: true
  hibernate:
   ddl-auto: none
 datasource:
  platform: h2
  schema: classpath:schema.sql
  data: classpath:data.sql
 application:
    name: aaa-provide-user-v1
logging:
 level:
  root: INFO
  org.hibernate: INFO
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  com.zgq: DEBUG
eureka: 
  client:
    serviceUrl:
      defaultZone: http://user:user123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    #metadata-map:
      #zone: ABC
      #zhangguiqing: sss
    #lease-renewal-interval-in-seconds: 5
    #appname: User-Service-HHHHHH
    